### ISSUE TITLE
Small bug in calculating mullion offset

### ISSUE THREAD

**Issue by isaacliao** [TACC/MassivePixelEnvironment#10]
On line 238 of Configuration.java,

offsets_[1] = (minj)_tileRes_[1] + mini_bezels_[1];

should be:

offsets_[1] = (minj)_tileRes_[1] + minj_bezels_[1];

I was wondering why changing mullionHeight in configuration.xml didn't seem to be working correctly, causing tiles to become vertically offset from each other across vertical boundaries. Making this change fixed it.

Otherwise the package works great! Thanks for making it!

Isaac Liao
VIDI Lab
UC Davis

**Comment by bmwesting** [comment]
Hi Isaac,

Thanks for tracking down the issue. I'll update the code to perform bezel compensation correctly and issue a new version.

Thanks,
Brandt

**Comment by bmwesting** [comment]
Fixed in commit b80f4c4ae0c03769ec6a86f264b7b05747396b87. Updated binary to follow by 5PM CST.
